### ISSUE TITLE
申请加入/更改方式

### ISSUE THREAD

**Issue by UserUnknownX** [OIer-Meet-Dev-Team/oier-meet-dev-team.github.io#1]
请单独创建issue以申请加入

并选择标签“申请”

使用 issue 2 的模板

**Comment by Sam2007-coder** [comment]
本 issue 下方不准进行无意义回复和对数据的处理

**Comment by bear-good** [comment]
> 请单独创建issue以申请加入
> 
> 并选择标签“申请”
> 
> 使用issue 2的模板

没有找到模板
