### ISSUE TITLE
数据收集

### ISSUE THREAD

**Issue by Aksadfjh** [OIer-Meet-Dev-Team/oier-meet-dev-team.github.io#10]
提供数据格式：**`比赛名称`+`空格`+`准考证号`+`空格`+`OJ名称`+`@`+`用户名`+`(uid=`+`你的uid`+`)`**  
例：  
`CSp2020-S1 BJ-00653 Luogu@Trotyl(uid=128369)`  
`NOIp2019-pj BJ-00810 Luogu@Trotyl(uid=128369)`

**Comment by Sam2007-coder** [comment]
有问题可以在下方提问，禁止无意义回复！

**Comment by Inversentropir-36** [comment]
CSp2020-S1 HB-00275 Luogu@Inversentropir_36(uid=294745)
CSp2020-S1 HB-00013 Luogu@bovine__kebi(uid=294736)
CSp2020-S1 HB-00243 Luogu@IamnotTXN(uid=295504)

**Comment by fyc-1358** [comment]
CSp2020-S1 ZJ-00834 Luogu@迟暮天复明(uid=222865)

**Comment by fyc-1358** [comment]
CSp2020-J1 ZJ-00834 Luogu@迟暮天复明(uid=222865)
CSp2020-S1 ZJ-00326 Luogu@迟暮天复明(uid=222865)

**Comment by VectorCN** [comment]
CSp2020-S1 JX-00279 Luogu@Vector_(uid=126763)

**Comment by jwjawa** [comment]
`CSp2020-S1 HB-00105 Luogu@_jwj_(uid=187543)`

**Comment by xiao-lin52** [comment]
CSp2020-J1 SC-00960 Luogu@Segment_Tree_(uid=183235)

CSp2020-S1 SC-01056 Luogu@Segment_Tree_(uid=183235)

**Comment by milkycoffee527** [comment]
CSp2020-J1 BJ-01105 Luogu@牛奶小咖啡(uid=317198)

CSp2020-S1 BJ-00451 Luogu@牛奶小咖啡(uid=317198)

**Comment by suxxsfe** [comment]
CSp2020-S1 SD-02167 Luogu@suxxsfe(uid=164432)

**Comment by qz-cqy** [comment]
@TNTtian 

 CSp2020-S1 BJ-00023 Luogu@rui_er(uid=122461)

另外，`NOIP2019-pj` 好评（（（

**Comment by OIer-deadX** [comment]
CSp2020-S1 ZJ-00112 Luogu@dead_X(uid=111055)

**Comment by tiger0132** [comment]
CSp2020-S1 HN-00228 Luogu@tiger0133(uid=28762)

**Comment by Resorie** [comment]
CSp2020-S1 JS-01001 Luogu@Sya_Resory(uid=114082)
CSp2020-J1 JS-01913 Luogu@Sya_Resory(uid=114082)

**Comment by wangmaohua-20090908** [comment]
CSp2020-J1 LN-00290 Luogu@wangmaohua20090908(uid=107484)
CSp2020-S1 LN-00186 Luogu@wangmaohua20090908(uid=107484)

**Comment by 32thirtytwo** [comment]
CSP 2020 普及 AH-02452 洛谷 @SIXIANG (uid=298549)
CSP 2020 提高 AH-0725 洛谷 @SIXIANG (uid=298549)

**Comment by 32thirtytwo** [comment]
CSp2020-S1 AH-02452 Luogu@SIXIANG(uid=298549)
CSp2020-J1 AH-0725 Luogu@SIXIANG(uid=298549)

**Comment by 32thirtytwo** [comment]
CSp2020-J1 AH-02452 Luogu@SIXIANG(uid=298549)
CSp2020-S1 AH-0725 Luogu@SIXIANG(uid=298549)

**Comment by s-y-c** [comment]
CSp2020-J1 HN-00971 Luogu@无敌的蒟蒻(uid=151647)

CSp2020-S1 HN-00383 Luogu@无敌的蒟蒻(uid=151647)

**Comment by lianjiaming** [comment]
CSp2020-J1 JS-01189 Luogu@Jimmy_Lian(uid=177435)

**Comment by Wowing** [comment]
CSp2020-J1 ZJ-00548 Luogu@Negative_Number(uid=93263)

**Comment by RedreamMer** [comment]
CSp2020-S1 ZJ-02169 Luogu@RedreamMer(uid=184549)

**Comment by zcmimi** [comment]
CSp2020-S1 GD-不知道 Luogu@zcmimi(uid=36532)

**Comment by chenhanzhou** [comment]
CSp2020-J1 BJ-00198 Luogu@刀锋上的人(uid=324038)

**Comment by ljm1621** [comment]
CSp2020-S2 BJ-00063 Luogu@ljm1621(uid=335799)

**Comment by ljm1621** [comment]
CSp2020-J2 BJ-00093 Luogu@ljm1621(uid=335799)

**Comment by chenhanzhou** [comment]
CSp2020-J2 BJ-00077 Luogu@刀锋上的人(uid=324038)

**Comment by Icantakioi** [comment]
**CSp2020-J1 AH-03255 Luogu@_•́へ•́╬_(uid=90693)
CSp2020-S1 AH-00968 Luogu@_•́へ•́╬_(uid=90693)
CSp2020-J2 AH-01096 Luogu@_•́へ•́╬_(uid=90693)
CSp2020-S2 AH-00395 Luogu@_•́へ•́╬_(uid=90693)**

**Comment by TNTdeD** [comment]
CSp2021-J1 SD-08085 Luogu@TNTdeD(uid=351132)

**Comment by fyc-1358** [comment]
CSp2021-S1 ZJ-00335 Luogu@迟暮天复明(uid=222865)
