### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by wenjunrui** [OIer-Meet-Dev-Team/oier-meet-dev-team.github.io#6]
<tr>
	<th>HN-01194</th>
	<th>Luogu</th>
	<th>@cnyz(uid=175829)</th>
</tr>

**Comment by wenjunrui** [comment]
```
<!--J-->
<tr>
	<th>HN-01194</th>
	<th>Luogu</th>
	<th>@cnyz(uid=175829)</th>
</tr>
```

**Comment by UserUnknownX** [comment]
> ```
> 
> <tr>
> 	<th>HN-01194</th>
> 	<th>Luogu</th>
> 	<th>@cnyz(uid=175829)</th>
> </tr>
> ```

已添加，感谢您的贡献
